CREATE TABLE CATEGORIA (
  CAT_ID SERIAL  NOT NULL ,
  CAT_NOME VARCHAR(50)      ,
PRIMARY KEY(CAT_ID));




CREATE TABLE ENTIDADE (
  ENT_ID SERIAL  NOT NULL ,
  MUN_ID INTEGER   NOT NULL ,
  ENT_NOME VARCHAR(60)   NOT NULL ,
  ENT_EMAIL VARCHAR(100)    ,
  ENT_TIPO CHAR(1)   NOT NULL ,
  ENT_RUA VARCHAR(100)   NOT NULL ,
  ENT_NUMERO VARCHAR(15)    ,
  ENT_BAIRRO VARCHAR(40)    ,
  ENT_FONE INTEGER      ,
PRIMARY KEY(ENT_ID)  );


CREATE INDEX ENTIDADE_FKIndex1 ON ENTIDADE (MUN_ID);




CREATE TABLE ESTADO (
  EST_UF SERIAL  NOT NULL ,
  EST_NOME VARCHAR(60)   NOT NULL   ,
PRIMARY KEY(EST_UF));




CREATE TABLE ITEM_PEDIDO (
  IPE_ID SERIAL  NOT NULL ,
  PRO_ID INTEGER   NOT NULL ,
  PED_ID INTEGER   NOT NULL ,
  IPE_UNITARIO FLOAT    ,
  IPE_TOTAL FLOAT    ,
  IPE_VALOR_ENTREGA FLOAT    ,
  IPE_QUANTIDADE FLOAT    ,
  IPE_STATUS CHAR(1)      ,
PRIMARY KEY(IPE_ID)    );


CREATE INDEX ITEM_PEDIDO_FKIndex1 ON ITEM_PEDIDO (PED_ID);
CREATE INDEX ITEM_PEDIDO_FKIndex2 ON ITEM_PEDIDO (PRO_ID);




CREATE TABLE MARCA (
  MAR_ID SERIAL  NOT NULL ,
  MAR_NOME VARCHAR(50)      ,
PRIMARY KEY(MAR_ID));




CREATE TABLE MUNICIPIO (
  MUN_ID SERIAL  NOT NULL ,
  EST_UF CHAR(2)   NOT NULL ,
  MUN_NOME VARCHAR(60)   NOT NULL   ,
PRIMARY KEY(MUN_ID)  );


CREATE INDEX MUNICIPIO_FKIndex1 ON MUNICIPIO (EST_UF);




CREATE TABLE PEDIDO (
  PED_ID SERIAL  NOT NULL ,
  ENT_FORNECEDOR INTEGER   NOT NULL ,
  ENT_CLIENTE INTEGER   NOT NULL ,
  PED_DATA TIMESTAMP    ,
  PED_REQUISICAO_CLIENTE INTEGER      ,
PRIMARY KEY(PED_ID)    );


CREATE INDEX PEDIDO_FKIndex1 ON PEDIDO (ENT_CLIENTE);
CREATE INDEX PEDIDO_FKIndex2 ON PEDIDO (ENT_FORNECEDOR);




CREATE TABLE PONTUACAO (
  PON_ID SERIAL  NOT NULL ,
  ENT_PONTUADO INTEGER   NOT NULL ,
  ENT_PONTUADOR INTEGER   NOT NULL ,
  PON_PONTUACAO INTEGER    ,
  PON_ANOTACAO VARCHAR(150)      ,
PRIMARY KEY(PON_ID)    );


CREATE INDEX PONTUACAO_FKIndex1 ON PONTUACAO (ENT_PONTUADOR);
CREATE INDEX PONTUACAO_FKIndex2 ON PONTUACAO (ENT_PONTUADO);




CREATE TABLE PRODUTO (
  PRO_ID SERIAL  NOT NULL ,
  CAT_ID INTEGER   NOT NULL ,
  MAR_ID INTEGER   NOT NULL ,
  PRO_NOME VARCHAR(100)    ,
  PRO_DISPONIVEL BOOL      ,
PRIMARY KEY(PRO_ID)    );


CREATE INDEX PRODUTO_FKIndex2 ON PRODUTO (MAR_ID);
CREATE INDEX PRODUTO_FKIndex3 ON PRODUTO (CAT_ID);




CREATE TABLE TABELA_PRECO (
  TAB_ID SERIAL  NOT NULL ,
  ENT_ID INTEGER   NOT NULL ,
  PRO_ID INTEGER   NOT NULL ,
  TAB_PRECO FLOAT    ,
  TAB_DATA TIMESTAMP    ,
  TAB_VALOR_KM FLOAT      ,
PRIMARY KEY(TAB_ID)    );


CREATE INDEX TABELA_PRECO_FKIndex1 ON TABELA_PRECO (PRO_ID);
CREATE INDEX TABELA_PRECO_FKIndex2 ON TABELA_PRECO (ENT_ID);




