CREATE TABLE PRODUTO (
	PRO_ID INTEGER  NOT NULL,
	PRO_NOME TEXT,
	PRIMARY KEY(PRO_ID)
);

CREATE TABLE PEDIDO (
	PED_CODIGO INTEGER NOT NULL,
	PED_DATA REAL,
	PED_LATITUDE INTEGER,
	PED_LONGITUDE INTEGER,
	PRIMARY KEY(PED_CODIGO)
);

CREATE TABLE PEDIDO_ITEM (
	PED_CODIGO INTEGER  NOT NULL,
	PEI_ITEM INTEGER  NOT NULL,
	PRO_ID INTEGER  NOT NULL,
	PEI_QUANTIDADE REAL,
	PRIMARY KEY(PED_CODIGO, PEI_ITEM),
	CONSTRAINT PED_CODIGO_FK FOREIGN KEY (PED_CODIGO)
		REFERENCES PEDIDO(PED_CODIGO),
	CONSTRAINT PRO_ID_FK FOREIGN KEY (PRO_ID)
		REFERENCES PRODUTO(PRO_ID)
);

CREATE INDEX PED_CODIGO_IDX ON PEDIDO_ITEM (PED_CODIGO);
CREATE INDEX PRO_ID_IDX ON PEDIDO_ITEM (PRO_ID);